### ISSUE TITLE
Where do you get the EDS file from?

### ISSUE THREAD

**Issue by therishidesai** [skpang/PiCAN2_CANopen_test#1]
I am looking through the NanoTec website and can't find where to get the EDS file from to use CANOpen.

**Comment by skpang** [comment]
You can use the eds from GitHub:
https://github.com/skpang/PiCAN2_CANopen_test/blob/master/CL3.eds

**Comment by victor20017** [comment]
But what if I want to obtain the EDS file from my own motor?

**Comment by FergalDuggan99** [comment]
You can find the EDS files for Nanotec controllers in the download folder of the Plug and Drive Studio software (https://www.nanotec.com/eu/en/products/2533-plug-drive-studio-2)
